name: e2e-integration

on:
  pull_request:
    branches: [main]

concurrency:
  group: e2e-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-components-vite:
    if: github.repository == 'kennylam/csb-build-no-vite'
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: ["14.x"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react build
      - name: Build CDN components
        run: yarn build:components
        working-directory: packages/web-components
      - name: Run e2e codesandbox tests
        run: yarn test:e2e:build && yarn test:e2e:test:no-percy
        working-directory: packages/web-components
      - uses: act10ns/slack@v1
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
  react-vite:
    if: github.repository == 'kennylam/csb-build-no-vite'
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: ["14.x"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-services-store --ignore @carbon/ibmdotcom-web-components build
      - name: Run e2e codesandbox tests
        run: yarn test:e2e:build && yarn test:e2e:test:no-percy
        working-directory: packages/react
      - uses: act10ns/slack@v1
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
