name: e2e-integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: e2e-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-components-vite:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ["14.x"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Run e2e codesandbox tests
        run: yarn test:e2e:build && yarn test:e2e:test:no-percy
        working-directory: packages/web-components
      - uses: act10ns/slack@v1
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
